### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by LightGlobal** [csbun/generator-actcmp#1]
grunt install命令报错，解决文案：把原本的Gruntfile.js中的bower-install-simple配置改成options:{directory: 'bower_components/'}

**Comment by csbun** [comment]
按照源码更新 bower-install-simple 到 `~1.0.3`，更新 Gruntfile.js 中的 bower-install-simple 配置：

``` javascript
        'bower-install-simple': {
            options: {},
            prod: {
                options: {
                    production: true
                }
            }
        },
```

或者直接重新运行 `yo actcmp`
